<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-28161K9" failures="1" tests="1" name="Default test" time="23.58" errors="0" timestamp="2023-04-09T23:38:41 IST">
  <testcase classname="webcheckoutTest.ActionsClass" name="getbrokenList" time="23.492">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	 expected [true] but found [false],
	The link with TextBroken Link is broken with code404 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
 expected [true] but found [false],
The link with TextBroken Link is broken with code404 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at webcheckoutTest.ActionsClass.getbrokenList(ActionsClass.java:147)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- getbrokenList -->
  <testcase classname="webcheckoutTest.ActionsClass" name="handloScroll" time="0.0">
    <ignored/>
  </testcase> <!-- handloScroll -->
  <testcase classname="webcheckoutTest.ActionsClass" name="calenderHandle" time="0.0">
    <ignored/>
  </testcase> <!-- calenderHandle -->
  <testcase classname="webcheckoutTest.ActionsClass" name="actionsExample" time="0.0">
    <ignored/>
  </testcase> <!-- actionsExample -->
  <testcase classname="webcheckoutTest.ActionsClass" name="getLinkCount" time="0.0">
    <ignored/>
  </testcase> <!-- getLinkCount -->
  <testcase classname="webcheckoutTest.ActionsClass" name="sslCheck" time="0.0">
    <ignored/>
  </testcase> <!-- sslCheck -->
  <testcase classname="webcheckoutTest.ActionsClass" name="windowHandler" time="0.0">
    <ignored/>
  </testcase> <!-- windowHandler -->
</testsuite> <!-- Default test -->
